# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nico/projects/3Dengine2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nico/projects/3Dengine2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nico/projects/3Dengine2/CMakeFiles /home/nico/projects/3Dengine2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nico/projects/3Dengine2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tolima

# Build rule for target.
tolima: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tolima
.PHONY : tolima

# fast build rule for target.
tolima/fast:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/build
.PHONY : tolima/fast

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Clipper.o: src/Clipper.cpp.o

.PHONY : src/Clipper.o

# target to build an object file
src/Clipper.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Clipper.cpp.o
.PHONY : src/Clipper.cpp.o

src/Clipper.i: src/Clipper.cpp.i

.PHONY : src/Clipper.i

# target to preprocess a source file
src/Clipper.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Clipper.cpp.i
.PHONY : src/Clipper.cpp.i

src/Clipper.s: src/Clipper.cpp.s

.PHONY : src/Clipper.s

# target to generate assembly for a file
src/Clipper.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Clipper.cpp.s
.PHONY : src/Clipper.cpp.s

src/Loader.o: src/Loader.cpp.o

.PHONY : src/Loader.o

# target to build an object file
src/Loader.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Loader.cpp.o
.PHONY : src/Loader.cpp.o

src/Loader.i: src/Loader.cpp.i

.PHONY : src/Loader.i

# target to preprocess a source file
src/Loader.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Loader.cpp.i
.PHONY : src/Loader.cpp.i

src/Loader.s: src/Loader.cpp.s

.PHONY : src/Loader.s

# target to generate assembly for a file
src/Loader.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Loader.cpp.s
.PHONY : src/Loader.cpp.s

src/Matrix.o: src/Matrix.cpp.o

.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i

.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s

.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/Object.o: src/Object.cpp.o

.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i

.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s

.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/Point.o: src/Point.cpp.o

.PHONY : src/Point.o

# target to build an object file
src/Point.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Point.cpp.o
.PHONY : src/Point.cpp.o

src/Point.i: src/Point.cpp.i

.PHONY : src/Point.i

# target to preprocess a source file
src/Point.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Point.cpp.i
.PHONY : src/Point.cpp.i

src/Point.s: src/Point.cpp.s

.PHONY : src/Point.s

# target to generate assembly for a file
src/Point.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Point.cpp.s
.PHONY : src/Point.cpp.s

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Shader.o: src/Shader.cpp.o

.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/TriMesh.o: src/TriMesh.cpp.o

.PHONY : src/TriMesh.o

# target to build an object file
src/TriMesh.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/TriMesh.cpp.o
.PHONY : src/TriMesh.cpp.o

src/TriMesh.i: src/TriMesh.cpp.i

.PHONY : src/TriMesh.i

# target to preprocess a source file
src/TriMesh.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/TriMesh.cpp.i
.PHONY : src/TriMesh.cpp.i

src/TriMesh.s: src/TriMesh.cpp.s

.PHONY : src/TriMesh.s

# target to generate assembly for a file
src/TriMesh.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/TriMesh.cpp.s
.PHONY : src/TriMesh.cpp.s

src/Triangle.o: src/Triangle.cpp.o

.PHONY : src/Triangle.o

# target to build an object file
src/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Triangle.cpp.o
.PHONY : src/Triangle.cpp.o

src/Triangle.i: src/Triangle.cpp.i

.PHONY : src/Triangle.i

# target to preprocess a source file
src/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Triangle.cpp.i
.PHONY : src/Triangle.cpp.i

src/Triangle.s: src/Triangle.cpp.s

.PHONY : src/Triangle.s

# target to generate assembly for a file
src/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/Triangle.cpp.s
.PHONY : src/Triangle.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/tolima.dir/build.make CMakeFiles/tolima.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tolima"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Clipper.o"
	@echo "... src/Clipper.i"
	@echo "... src/Clipper.s"
	@echo "... src/Loader.o"
	@echo "... src/Loader.i"
	@echo "... src/Loader.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/Point.o"
	@echo "... src/Point.i"
	@echo "... src/Point.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/TriMesh.o"
	@echo "... src/TriMesh.i"
	@echo "... src/TriMesh.s"
	@echo "... src/Triangle.o"
	@echo "... src/Triangle.i"
	@echo "... src/Triangle.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

